### PR TITLE
[CI] Add automated test with Coq 8.9+beta1

### PR DESCRIPTION
**Pull request by erikmd**
Add test-build with `coqorg/coq:8.9` as suggested in https://github.com/coq-community/paramcoq/pull/8#issuecomment-436251557

### CODE REVIEW

**Comment by erikmd** [comment]
@Zimmi48 I've also updated https://github.com/coq-community/docker-coq/wiki#supported-tags

@proux01 Beyond this PR, you might want to remove the `allow_failures: […] "coqorg/coq:dev"` setting as you fixed the `coq.dev` compatibility (or you may also decide to keep the configuration as is)

**Comment by proux01** [comment]
@erikmd: thanks! Indeed, removing the allow_failures would make sense. Could you also please change the `cd test-suite; make` in `cd test-suite; make examples` (or make `examples` the first rule in the Makefile) so that to actually run the whole test suite (and not just parametricity.vo)? (this will make dev fail as there is still a small bug to be fixed there)

**Comment by erikmd** [comment]
@proux01 good idea to run all examples as well, however I am afraid the output of one of them is extremely verbose (>21900 LoC) so maybe one can disable just this one?

**Comment by erikmd** [comment]
Namely it is `bug4.vo` which contains Set Parametricity Debug.
So I suggest to keep `make bug4.vo` but replace this line with (* Set Parametricity Debug. *)

**Comment by erikmd** [comment]
This is now done, and I also removed the `allow_failures` setting as you suggested.

**Comment by proux01** [comment]
Perfect

**Pull request merged**
