### PR TITLE
Add -no-template-check for examples until we fix the code for generating

### PR DESCRIPTION
**Pull request by mattam82**
parametric versions of template-polymorphic inductives

### CODE REVIEW

**Comment by mattam82** [comment]
This is an overlay for coq/coq#9918

**Comment by vbgl** [comment]
FTR, we’ll need a similar patch applied to the `v8.10` branch.

**Comment by Zimmi48** [comment]
Note: this overlay is not backward compatible and thus should be merged in sync with the corresponding Coq PR. But changing this patch to use `-set "Template Check=false"` instead of `-no-template-check` would actually be backward compatible and allow merging this PR in `master` and `v8.10` earlier.

**Comment by vbgl** [comment]
I’ve implemented the proposition from Théo in #41.

**Comment by proux01** [comment]
#41 merged and cherry-picked in the v8.10 branch. I'm closing this one.

**Pull request closed without merging**
