### PR TITLE
use only Docker-based CI for 8.14

### PR DESCRIPTION
**Pull request by palmskog**
Since the Docker image with 8.14+rc1 is now out, use only this in the `v8.14` branch CI.

### CODE REVIEW

**Comment by proux01** [comment]
Thanks @palmskog (you were faster than me, I was about to do it ;) )

**Comment by proux01** [comment]
@palmskog I just made the releases, I'm unsure of the process for opam packages: should I temporarily put them in extra-dev, or directly in released?

**Comment by Zimmi48** [comment]
Yes, that's correct.

**Comment by proux01** [comment]
Sorry, which one?

**Comment by palmskog** [comment]
`extra-dev`

**Comment by palmskog** [comment]
But to be extra clear, if there will be a release for 8.13 as well (as I hope there will be), then that should of course go in `released`.

**Pull request merged**
