### PR TITLE
[CI] Make Travis use the Docker-Coq images and run the test suite

### PR DESCRIPTION
**Pull request by erikmd**
Dear Paramcoq maintainers,

This is a proposal to migrate the current implementation of the Travis CI config to a Docker-based test build. This relies on the newest [Docker-Coq](https://hub.docker.com/r/coqorg/coq/) images (which have been elaborated in coq/coq#7753).
This approach should speed-up the CI builds (as Coq is precompiled in the image) and avoid the caching issues that could arise in the previous non-docker approach (e.g., non-availability of the opam cache if we test-build a new git branch).

Before merging this PR, someone will need to enable the Travis CI / GItHub integration for this repository (preferably using https://travis-ci.com, since it has been said to [replace travis-ci.org in the long run](https://devops.stackexchange.com/a/4305/10156)).

(*Note:* as the CI reported [on my fork](https://travis-ci.com/erikmd/paramcoq), the current version of the codebase make Coq 8.7 and 8.8 happy, while the `src.8.10` code doesn't compile with latest Coq master.)

This PR also adds the command `cd test-suite; make` in the CI test-build and improves the corresponding Makefile.

Kind regards

### CODE REVIEW

**Comment by Zimmi48** [comment]
paramcoq activated on travis-ci.org (and not travis-ci.com because it had been activated there in the past). I can send an e-mail to manually migrate the project to travis-ci.com.

Closing and reopening to trigger the build.

**Comment by Zimmi48** [comment]
Note that ideally, one would also want to test the 8.9 version.

**Comment by erikmd** [comment]
@Zimmi48
> paramcoq activated on travis-ci.org

OK thanks!

> I can send an e-mail to manually migrate the project to travis-ci.com.

Thanks for proposing! According to [this page](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg) this indeed seems useful to do this now rather than later, as the migration won't necessarily preserve the build history.

> one would also want to test the 8.9 version.

Sure, I just need to wait that Coq 8.9 is on OPAM, then I'll readily publish another image `coqorg/coq:8.9`. Fell free to ping me in due time.

**Comment by Zimmi48** [comment]
>Thanks for proposing! According to this page this indeed seems useful to do this now rather than later, as the migration won't necessarily preserve the build history.

I've sent the request.

**Comment by Zimmi48** [comment]
It worked. The Checks tab allows to see the details of each job, in particular how the build with Coq master failed but is allowed to.

**Comment by Zimmi48** [comment]
This looks good to me although I don't especially understand the changes to the makefiles.

@proux01 WDYT?

**Comment by Zimmi48** [comment]
@erikmd An opam package is now available for 8.9+beta1 (coq/opam-coq-archive#504 was just merged).

**Comment by erikmd** [comment]
@Zimmi48 I forgot to @-mention you in my latest comment :)

Regarding the changes to these Makefiles: it is mostly some refactoring to remove duplication of rules, and the addition of a configuration step for Coq 8.7 in order to be able to run the test-suite with all versions of Coq (the test-suite theory was not run in the previous version of `.travis.yml`, and this theory happened to be incompatible with Coq 8.7 because of the `Decimal` module).

I'm going to do a partial squash to remove the fixup commit, and add a commit with a badge for the `README.md`. Thanks for the help with the travis-ci.com migration!

**Comment by erikmd** [comment]
@Zimmi48 
> It seems worth, especially for testing plugins such as this one, but probably not a good idea to have the latest image correspond to the beta version.

OK I agree with your suggestion; I have just implemented that approach: the `coqorg/coq:8.9-beta1` build is now in progress and will automatically be tagged `coqorg/coq:8.9`, but not `coqorg/coq:latest`.

**Comment by ejgallego** [comment]
> Indeed, 8.10 is currently broken. Well, that's what CI is for. I'm looking at it and I'll try to catch up with coq master.

We will add paramcoq to Coq's CI indeed so this won't happen again. But I'd be good if we could fix come to a conclusion with #9

**Comment by erikmd** [comment]
I've just opened coq/opam-coq-archive#507 that should solve the issue with the `coqorg/coq:8.9` image.

**Pull request merged**
